-- 입력/선택/변경 이력 백업용 로그 테이블입니다.
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text not null default '',
  entity_id text not null default '',
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
on public.audit_logs (created_at desc, id desc);

create index if not exists audit_logs_entity_idx
on public.audit_logs (entity_type, entity_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists "anon users can manage audit logs" on public.audit_logs;
drop policy if exists audit_logs_anon_all on public.audit_logs;

create policy audit_logs_anon_all
on public.audit_logs
for all
to anon
using (true)
with check (true);

grant usage on schema public to anon;
grant all on public.audit_logs to anon;
grant usage, select on all sequences in schema public to anon;

select
  'audit_logs table' as check_item,
  count(*) as row_count
from information_schema.tables
where table_schema = 'public'
  and table_name = 'audit_logs';
