-- 발주금액 입력 및 최종발주목록 관리를 위한 DB 패치입니다.
-- Supabase SQL Editor에서 전체 실행하세요.

alter table public.draft_orders
add column if not exists order_amount numeric not null default 0;

update public.draft_orders
set order_amount = qty * unit_price
where order_amount = 0
  and unit_price > 0;

alter table public.draft_orders
drop constraint if exists draft_orders_order_amount_check;

alter table public.draft_orders
add constraint draft_orders_order_amount_check check (order_amount >= 0);

create table if not exists public.final_orders (
  id bigint generated by default as identity primary key,
  order_no text not null,
  item_name text not null,
  qty numeric not null check (qty >= 0),
  unit text not null,
  order_amount numeric not null default 0 check (order_amount >= 0),
  status text not null default 'ordered'
    check (status in ('ordered', 'received', 'cancelled')),
  memo text not null default '',
  ordered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.final_orders
add column if not exists order_no text;

alter table public.final_orders
add column if not exists item_name text;

alter table public.final_orders
add column if not exists qty numeric not null default 0;

alter table public.final_orders
add column if not exists unit text not null default 'g';

alter table public.final_orders
add column if not exists order_amount numeric not null default 0;

alter table public.final_orders
add column if not exists status text not null default 'ordered';

alter table public.final_orders
add column if not exists memo text not null default '';

alter table public.final_orders
add column if not exists ordered_at timestamptz not null default now();

alter table public.final_orders
add column if not exists updated_at timestamptz not null default now();

update public.final_orders
set order_no = coalesce(order_no, 'PO-MIGRATED-' || id::text),
    item_name = coalesce(item_name, ''),
    status = coalesce(status, 'ordered'),
    memo = coalesce(memo, ''),
    ordered_at = coalesce(ordered_at, now()),
    updated_at = coalesce(updated_at, now());

alter table public.final_orders
alter column order_no set not null;

alter table public.final_orders
alter column item_name set not null;

alter table public.final_orders
drop constraint if exists final_orders_qty_check;

alter table public.final_orders
add constraint final_orders_qty_check check (qty >= 0);

alter table public.final_orders
drop constraint if exists final_orders_order_amount_check;

alter table public.final_orders
add constraint final_orders_order_amount_check check (order_amount >= 0);

alter table public.final_orders
drop constraint if exists final_orders_status_check;

alter table public.final_orders
add constraint final_orders_status_check check (status in ('ordered', 'received', 'cancelled'));

create index if not exists final_orders_ordered_at_idx
on public.final_orders (ordered_at desc, id desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists final_orders_touch_updated_at on public.final_orders;
create trigger final_orders_touch_updated_at
before update on public.final_orders
for each row execute function public.touch_updated_at();

alter table public.final_orders enable row level security;

drop policy if exists "anon users can manage final orders" on public.final_orders;
drop policy if exists final_orders_anon_all on public.final_orders;

create policy final_orders_anon_all
on public.final_orders
for all
to anon
using (true)
with check (true);

grant usage on schema public to anon;
grant all on public.draft_orders to anon;
grant all on public.final_orders to anon;
grant usage, select on all sequences in schema public to anon;

select
  'draft_orders.order_amount' as check_item,
  count(*) as row_count
from information_schema.columns
where table_schema = 'public'
  and table_name = 'draft_orders'
  and column_name = 'order_amount'
union all
select
  'final_orders table' as check_item,
  count(*) as row_count
from information_schema.tables
where table_schema = 'public'
  and table_name = 'final_orders';
