-- 식단표 관리 페이지용 테이블과 2026년 8월 기본 식단입니다.
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  plan_date date not null,
  slot integer not null default 1 check (slot between 1 and 3),
  menu_name text not null,
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_date, slot)
);

create index if not exists meal_plans_date_idx
on public.meal_plans (plan_date, slot);

drop trigger if exists meal_plans_touch_updated_at on public.meal_plans;
create trigger meal_plans_touch_updated_at
before update on public.meal_plans
for each row execute function public.touch_updated_at();

alter table public.meal_plans enable row level security;
drop policy if exists "anon users can manage meal plans" on public.meal_plans;
create policy "anon users can manage meal plans"
on public.meal_plans for all
to anon
using (true)
with check (true);

grant all on public.meal_plans to anon;
grant usage, select on sequence public.meal_plans_id_seq to anon;

insert into public.meal_plans (plan_date, slot, menu_name)
values
  ('2026-08-03', 1, '비빔밥'), ('2026-08-03', 2, '유부장국'),
  ('2026-08-04', 1, '닭갈비'), ('2026-08-04', 2, '미역국'),
  ('2026-08-05', 1, '소불고기'), ('2026-08-05', 2, '된장찌개'),
  ('2026-08-06', 1, '소야볶음'), ('2026-08-06', 2, '목살김치찌개'),
  ('2026-08-07', 1, '제육볶음'), ('2026-08-07', 2, '계란국'),
  ('2026-08-10', 1, '닭볶음탕'), ('2026-08-10', 2, '시금치된장국'),
  ('2026-08-11', 1, '유산슬덮밥'), ('2026-08-11', 2, '계란국'),
  ('2026-08-12', 1, '카레덮밥'), ('2026-08-12', 2, '미소된장국'),
  ('2026-08-13', 1, '김치전'), ('2026-08-13', 2, '닭곰탕'),
  ('2026-08-14', 1, '김치볶음밥'), ('2026-08-14', 2, '어묵국'),
  ('2026-08-17', 1, '우삼겹숙주볶음'), ('2026-08-17', 2, '미소된장국'),
  ('2026-08-18', 1, '유니짜장'), ('2026-08-18', 2, '김치어묵콩나물국'),
  ('2026-08-19', 1, '삼겹김치찜'), ('2026-08-19', 2, '계란국'),
  ('2026-08-20', 1, '돼지고기짜글이'), ('2026-08-20', 2, '황태국'),
  ('2026-08-21', 1, '불고기비빔밥'), ('2026-08-21', 2, '미소된장국'),
  ('2026-08-24', 1, '스팸계란구이'), ('2026-08-24', 2, '참치김치찌개'),
  ('2026-08-25', 1, '치킨마요덮밥'), ('2026-08-25', 2, '유부장국'),
  ('2026-08-26', 1, '햄계란말이'), ('2026-08-26', 2, '순대국밥'),
  ('2026-08-27', 1, '매콤닭볶음탕'), ('2026-08-27', 2, '북엇국'),
  ('2026-08-28', 1, '카레'), ('2026-08-28', 2, '얼큰콩나물국'),
  ('2026-08-31', 1, '계란말이'), ('2026-08-31', 2, '소고기육개장')
on conflict (plan_date, slot) do update
set menu_name = excluded.menu_name,
    updated_at = now();
