-- 직원 식단·발주 관리 v11 화면 기준 Supabase 스키마
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  base_servings integer not null default 20 check (base_servings > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  name text not null,
  qty numeric not null check (qty >= 0),
  unit text not null,
  ingredient_type text not null default 'main'
    check (ingredient_type in ('main', 'seasoning')),
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  qty numeric not null default 0 check (qty >= 0),
  unit text not null default 'g',
  memo text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.draft_orders (
  id bigint generated by default as identity primary key,
  item_name text not null,
  qty numeric not null check (qty >= 0),
  unit text not null,
  ingredient_type text not null default 'main'
    check (ingredient_type in ('main', 'seasoning')),
  unit_price numeric not null default 0 check (unit_price >= 0),
  order_amount numeric not null default 0 check (order_amount >= 0),
  memo text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.final_orders (
  id bigint generated by default as identity primary key,
  order_no text not null,
  item_name text not null,
  qty numeric not null check (qty >= 0),
  unit text not null,
  ingredient_type text not null default 'main'
    check (ingredient_type in ('main', 'seasoning')),
  order_amount numeric not null default 0 check (order_amount >= 0),
  status text not null default 'ordered'
    check (status in ('ordered', 'received', 'cancelled')),
  memo text not null default '',
  ordered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text not null default '',
  entity_id text not null default '',
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.inventory drop constraint if exists inventory_name_key;

create unique index if not exists inventory_name_unit_key
on public.inventory (name, unit);

create unique index if not exists recipe_ingredients_recipe_name_unit_key
on public.recipe_ingredients (recipe_id, name, unit);

drop index if exists public.draft_orders_item_name_unit_key;

create unique index if not exists draft_orders_item_name_unit_type_key
on public.draft_orders (item_name, unit, ingredient_type);

alter table public.final_orders
drop constraint if exists final_orders_order_no_key;

create index if not exists final_orders_ordered_at_idx
on public.final_orders (ordered_at desc, id desc);

create index if not exists audit_logs_created_at_idx
on public.audit_logs (created_at desc, id desc);

create index if not exists audit_logs_entity_idx
on public.audit_logs (entity_type, entity_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists recipes_touch_updated_at on public.recipes;
create trigger recipes_touch_updated_at
before update on public.recipes
for each row execute function public.touch_updated_at();

drop trigger if exists inventory_touch_updated_at on public.inventory;
create trigger inventory_touch_updated_at
before update on public.inventory
for each row execute function public.touch_updated_at();

drop trigger if exists draft_orders_touch_updated_at on public.draft_orders;
create trigger draft_orders_touch_updated_at
before update on public.draft_orders
for each row execute function public.touch_updated_at();

drop trigger if exists final_orders_touch_updated_at on public.final_orders;
create trigger final_orders_touch_updated_at
before update on public.final_orders
for each row execute function public.touch_updated_at();

alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.inventory enable row level security;
alter table public.draft_orders enable row level security;
alter table public.final_orders enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "anon users can manage recipes" on public.recipes;
create policy "anon users can manage recipes"
on public.recipes for all
to anon
using (true)
with check (true);

drop policy if exists "anon users can manage recipe ingredients" on public.recipe_ingredients;
create policy "anon users can manage recipe ingredients"
on public.recipe_ingredients for all
to anon
using (true)
with check (true);

drop policy if exists "anon users can manage inventory" on public.inventory;
create policy "anon users can manage inventory"
on public.inventory for all
to anon
using (true)
with check (true);

drop policy if exists "anon users can manage draft orders" on public.draft_orders;
create policy "anon users can manage draft orders"
on public.draft_orders for all
to anon
using (true)
with check (true);

drop policy if exists "anon users can manage final orders" on public.final_orders;
create policy "anon users can manage final orders"
on public.final_orders for all
to anon
using (true)
with check (true);

drop policy if exists "anon users can manage audit logs" on public.audit_logs;
create policy "anon users can manage audit logs"
on public.audit_logs for all
to anon
using (true)
with check (true);

grant usage on schema public to anon;
grant all on public.recipes to anon;
grant all on public.recipe_ingredients to anon;
grant all on public.inventory to anon;
grant all on public.draft_orders to anon;
grant all on public.final_orders to anon;
grant all on public.audit_logs to anon;
grant usage, select on all sequences in schema public to anon;
